# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ErrorViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1158, 604)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(30, 80, 341, 31))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 50, 89, 23))
        self.label.setObjectName("label")
        self.getErrorsButton = QtWidgets.QPushButton(Dialog)
        self.getErrorsButton.setGeometry(QtCore.QRect(500, 70, 171, 51))
        self.getErrorsButton.setObjectName("getErrorsButton")
        self.errorResultsEdit = QtWidgets.QTextEdit(Dialog)
        self.errorResultsEdit.setGeometry(QtCore.QRect(20, 200, 1091, 361))
        self.errorResultsEdit.setObjectName("errorResultsEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(520, 170, 89, 23))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        self.getErrorsButton.clicked.connect(Dialog.GetErrors) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Website"))
        self.getErrorsButton.setText(_translate("Dialog", "Get Errors"))
        self.label_2.setText(_translate("Dialog", "Errors"))
